### ISSUE TITLE
Missing capabilities for the implementation

### ISSUE THREAD

**Issue by timothyjward** [eclipse-osgi-technology/jakarta-webservices#9]
### Current Behavior

There is no implementation capability nor a service capability as required in the specification

### Expected Behavior

The capabilities should be provided by the implementation bundle

### Version

snapshot

### Are you interested in contributing a solution yourself?

None

**Comment by laeubi** [comment]
It has this here:

https://github.com/eclipse-osgi-technology/jakarta-webservices/blob/f88cbd272f970c4ba750541174555fc56c813b1a/runtime/registrar/src/main/java/org/eclipse/osgi/technology/webservices/registrar/EndpointRegistrar.java#L54

but ti seems it is not picked up by bnd build?

**Comment by timothyjward** [comment]
> but ti seems it is not picked up by bnd build?

I think it is being picked up, but the name being used is wrong. The constants update should improve things I think.

**Comment by laeubi** [comment]
> > but ti seems it is not picked up by bnd build?
> 
> I think it is being picked up, but the name being used is wrong. The constants update should improve things I think.

I was just confused because

> There is no implementation capability nor a service capability

seem to indicate that there is not any (including a wrong) at all.

**Comment by timothyjward** [comment]
This has improved, but:

The uses constraint for the service set at https://github.com/eclipse-osgi-technology/jakarta-webservices/blob/45db41cd0e730356bb19363620c7976a067a05d9/runtime/registrar/src/main/java/org/eclipse/osgi/technology/webservices/registrar/EndpointRegistrar.java#L63 does not match the requirement from the specification: 

    uses:="org.osgi.service.webservice.runtime,org.osgi.service.webservice.runtime.dto,jakarta.xml.ws.handler,jakarta.xml.ws,org.osgi.dto,org.osgi.framework.dto"

The uses constraint for the implementation set at https://github.com/eclipse-osgi-technology/jakarta-webservices/blob/45db41cd0e730356bb19363620c7976a067a05d9/runtime/registrar/src/main/java/org/eclipse/osgi/technology/webservices/registrar/EndpointRegistrar.java#L60 does not match the requirement from the specification: 

    uses:="org.osgi.service.webservice.runtime,org.osgi.service.webservice.runtime.dto,jakarta.xml.ws.handler,jakarta.xml.ws,org.osgi.dto,org.osgi.framework.dto" 


The value for the implementation set at https://github.com/eclipse-osgi-technology/jakarta-webservices/blob/45db41cd0e730356bb19363620c7976a067a05d9/runtime/registrar/src/main/java/org/eclipse/osgi/technology/webservices/registrar/EndpointRegistrar.java#L60 does not match the requirement from the specification: 

    osgi.webservice

**Comment by laeubi** [comment]
The uses constraints are automatically computed, so I would assume they are correct here, I don't know why it was requested to have more uses constraint in the spec.

**Comment by timothyjward** [comment]
> The uses constraints are automatically computed, so I would assume they are correct here, I don't know why it was requested to have more uses constraint in the spec.

For the capability annotation the uses constraint is computed based on the packages of the types that you pass in. The constraints should be appropriate for the capability type. The service requires you to use API, so it should be enough to list the one and only package. The implementation capability however needs to be a little more careful as people may only use a few of the packages.

I would expect

    uses:="org.osgi.service.webservice.runtime,org.osgi.service.webservice.runtime.dto"

and

    uses:="jakarta.xml.ws.handler,jakarta.xml.ws,jakarta.jws"

to be fine, but you're the expert.

**Comment by laeubi** [comment]
For the service itself I would only "use" `org.osgi.service.webservice.runtime` as runtime is exported with a use of `org.osgi.service.webservice.runtime.dto` this seems redundant to specify as there is no way to get wired to a different dto than the one with the runtime but not harmful to add it.

For the implementation `jakarta.xml.ws.handler` (to track the handlers) and the `jakarta.xml.ws` (for Endpoint specification) seem to be enough even though the later seems redundant as `jakarta.xml.ws` is used by the former,  `jakarta.jws` is not used, these only contains annotation we not process in any way.

I have now done this in:

- https://github.com/eclipse-osgi-technology/jakarta-webservices/pull/16

> does not match the requirement from the specification:
> osgi.webservice

I must confess I'm not sure what was the final decision after all the renaming, the java code currently uses `osgi.service.webservice` so either the code or the spec is not correct. I think we should fix it up in the spec-PR and I'll then adjust it here accordingly (if required).

**Comment by timothyjward** [comment]
> I must confess I'm not sure what was the final decision after all the renaming, the java code currently uses `osgi.service.webservice` so either the code or the spec is not correct. I think we should fix it up in the spec-PR and I'll then adjust it here accordingly (if required).

The TCK test for this is failing as a result of the inconsistency. If either is changed then it will still fail as the TCK also expects to see `org.osgi.service.webservice.runtime` in the uses list. The TCK is using the most recent version of the spec text that I can find, but can easily be changed if the spec text changes.

**Comment by laeubi** [comment]
@timothyjward with https://github.com/eclipse-osgi-technology/jakarta-webservices/commit/f6aeb83dbab983365676582e814d9de76b70941a I now listing relevant interfaces/classes  in the uses directive explicitly, can you please check if that satisfies your expectation now?

It is now

```
Provide-Capability
  osgi.implementation;osgi.implementation="osgi.service.webservice";version:Version="1.0";
      uses:="jakarta.xml.ws.handler,jakarta.xml.ws"
  osgi.service;objectClass:List<String>="org.osgi.service.webservice.runtime.WebserviceServiceRuntime";
      uses:="org.osgi.service.webservice.runtime,org.osgi.service.webservice.runtime.dto"
```

if you agree with that I would update the spec text accordingly and this ticket can be closed.

**Comment by timothyjward** [comment]
> [@timothyjward](https://github.com/timothyjward) with [f6aeb83](https://github.com/eclipse-osgi-technology/jakarta-webservices/commit/f6aeb83dbab983365676582e814d9de76b70941a) I now listing relevant interfaces/classes in the uses directive explicitly, can you please check if that satisfies your expectation now?
> 
> It is now
> 
> ```
> Provide-Capability
>   osgi.implementation;osgi.implementation="osgi.service.webservice";version:Version="1.0";
>       uses:="jakarta.xml.ws.handler,jakarta.xml.ws"
>   osgi.service;objectClass:List<String>="org.osgi.service.webservice.runtime.WebserviceServiceRuntime";
>       uses:="org.osgi.service.webservice.runtime,org.osgi.service.webservice.runtime.dto"
> ```
> 
> if you agree with that I would update the spec text accordingly and this ticket can be closed.


The service capability looks good, and is what the TCK tests for. The specification text lists [a larger number of packages](https://github.com/osgi/osgi/pull/845/files#diff-ccd25ff0a7196203a9a845adf287a27f7d98b32f21f3a922ce6f747f7e4418b9R501) which needs to be trimmed. One other fix in the specification text is that the service capability must be provided by the bundle which provides the `WebserviceServiceRuntime` service.


The implementation capability is missing a link to the specification packages. This is done to ensure that someone requiring the implementation doesn't wire to a different version of the specification packages and thus fail to be able to use the implementation. The TCK therefore adds [this](https://github.com/osgi/osgi/pull/845/files#diff-c73ace38b648a168a55a2f0337811d665240988a54a3a5b90aeccf365cea8e86R147) but the spec text has [this](https://github.com/osgi/osgi/pull/845/files#diff-ccd25ff0a7196203a9a845adf287a27f7d98b32f21f3a922ce6f747f7e4418b9R476)

If I were looking for maximum consistency with other specifications (e.g. servlet and rest whiteboards) then I would expect to see:

```
Provide-Capability
  osgi.implementation;osgi.implementation="osgi.webservice";version:Version="1.0";
      uses:="jakarta.xml.ws.handler,jakarta.xml.ws,org.osgi.service.webservice.whiteboard"
  osgi.service;objectClass:List<String>="org.osgi.service.webservice.runtime.WebserviceServiceRuntime";
      uses:="org.osgi.service.webservice.runtime,org.osgi.service.webservice.runtime.dto"
```

*And* I would expect the text around the examples to be explicit. Note that my suggestion also needs a constant value to be changed (the implementation capability name).

**Comment by laeubi** [comment]
I have now started a new PR to improve the specification here:

- https://github.com/osgi/osgi/pull/879/commits/142e4c50e02c32032a96663b04e0ca7f1202e7ec

if you think anything is still missing, just leave a note and I'll try to improve that as well.

**Comment by laeubi** [comment]
> The implementation capability is missing a link to the specification packages. 

What specifically do you mean? The implementation does only use the jakarta packages and the service capability already, the service capbilty is already listing the dto/registry and the import/export package already cover this as well so I don't see how ever the resolver would be able to wire an inconsistent state, requiring to list packages "just in case" seems not only superfluous but more confusing.

**Comment by timothyjward** [comment]
> > The implementation capability is missing a link to the specification packages.
> 
> What specifically do you mean? The implementation does only use the jakarta packages and the service capability already, the service capbilty is already listing the dto/registry and the import/export package already cover this as well so I don't see how ever the resolver would be able to wire an inconsistent state, requiring to list packages "just in case" seems not only superfluous but more confusing.

I specifically mean the specification whiteboard package. This uses constraint is used to ensure a link to the specification API where the API itself doesn't have a hard link to the client. It allows people to resolve and deploy the implementation with a consistent class space even when they don't register whiteboard services directly. This is done by other similar specifications:

- The [Servlet Whiteboard](https://docs.osgi.org/specification/osgi.cmpn/8.1.0/service.servlet.html#d0e88755)
- The [Jakarta Rest Whiteboard](https://docs.osgi.org/specification/osgi.cmpn/8.1.0/service.jakartars.html#d0e133014)
- [Declarative Services](https://docs.osgi.org/specification/osgi.cmpn/8.1.0/service.component.html#service.component-capabilities) (extender capability)
- [Typed Events](https://docs.osgi.org/specification/osgi.cmpn/8.1.0/service.typedevent.html#d0e152548)
- [JPA Service](https://docs.osgi.org/specification/osgi.cmpn/8.1.0/service.jpa.html#service.jpa-capabilities) (extender capability)

You can then ensure a consistent resolve/deployment by requiring the implementation capability and importing the base spec api package.

**Comment by laeubi** [comment]
> I specifically mean the specification whiteboard package. This uses constraint is used to ensure a link to the specification API where the API itself doesn't have a hard link to the client. 

I don't understand what you mean by client, we declare these packages:

- jakarta.xml.ws.handler
- jakarta.xml.ws
- org.osgi.service.webservice.whiteboard

what else do you suspect to being used by the implementation?

**Comment by laeubi** [comment]
@timothyjward since https://github.com/osgi/osgi/pull/879 is merged now I think this is fixed now?

**Comment by timothyjward** [comment]
I believe that we agree on the definition of the capabilities, however I think that the test in the TCK is still not passing. I've created the PR https://github.com/osgi/osgi/pull/952 in order to actually incorporate the spec chapter and TCK into the main OSGi release. You can see in the CI checks that the TCK is still not passing cleanly.
